# Lists and Tuples <hr style="border:2.5px solid rgb(28, 75, 147)"></hr>

<b>Sidney Louise G. Monillo</b>
<br><i>Computer Engineer/Technician</i>

In [1]:
# imports and packages

import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [2]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

In [3]:
np.shape(my_array)

(3,)

# 2D Array

In [4]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.shape(my_array)

(2, 3)

In [6]:
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
np.shape(t_array)

(3, 2)

# Measures of Central Tendency

In [8]:
# Jaguar vs Panther

resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [9]:
np.shape(resistance)

(2, 11)

In [10]:
# Mean

res_mean = np.nanmean(resistance, axis =1)
res_mean

array([ 9.4 , 10.75])

In [11]:
print("Jaguar Mean:" + str((res_mean[0]).round(2)) + " ohms")

Jaguar Mean:9.4 ohms


In [12]:
print(f'Jaguar:{res_mean[0]:.2f} ohms')
print(f'Panther:{res_mean[1]:.2f} ohms')

Jaguar:9.40 ohms
Panther:10.75 ohms


In [13]:
# Median

res_median = np.nanmedian(resistance, axis =1)
res_median

array([9.8 , 9.55])

In [14]:
print(f'Jaguar:{res_median[0]:.2f} ohms')
print(f'Jaguar:{res_median[1]:.2f} ohms')

Jaguar:9.80 ohms
Jaguar:9.55 ohms


In [15]:
# Mode

res_mode = stats.mode(resistance, axis = 1)
res_mode

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [16]:
jag_res = resistance[0]

print("Jaguar Mode:")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar Mode:
9.8 ohms
10.4 ohms


In [17]:
pan_res = resistance[1]

print("Panther Mode:")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther Mode:
9.1 ohms


# Measures of Variability

In [18]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [19]:
# Range

res_max = np.nanmax(resistance, axis = 1)
res_min = np.nanmin(resistance, axis = 1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [20]:
print(f'Jaguar range:{res_range[0]:.2f} ohms')
print(f'Panther range:{res_range[1]:.2f} ohms')

Jaguar range:8.00 ohms
Panther range:10.90 ohms


In [21]:
# IQR
res_Q1 = np.nanpercentile(resistance, 25, axis = 1)
res_Q1

array([9.4  , 9.125])

In [22]:
res_Q3 = np.nanpercentile(resistance, 75, axis = 1)
res_Q3

array([10.45 , 10.625])

In [23]:
print(f'Jaguar IQR: {res_Q3[0]-res_Q1[0]:.2f} ohms')
print(f'Panther IQR: {res_Q3[1]-res_Q1[1]:.2f} ohms')

Jaguar IQR: 1.05 ohms
Panther IQR: 1.50 ohms


In [24]:
res_var = np.nanvar(resistance, ddof = 1, axis = 1)

print(f'Jaguar Variance: {res_var[0]:.2f} ohms')
print(f'Panther Variance: {res_var[1]:.2f} ohms')

Jaguar Variance: 4.86 ohms
Panther Variance: 11.08 ohms


In [25]:
res_std = np.nanstd(resistance, ddof = 1, axis = 1)

print(f'Jaguar Variance: {res_std[0]:.2f} ohms')
print(f'Panther Variance: {res_std[1]:.2f} ohms')

Jaguar Variance: 2.20 ohms
Panther Variance: 3.33 ohms
